# Generated by Django 4.0 on 2022-03-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_goods', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('category', models.CharField(choices=[('other', 'Other'), ('laptops', 'Laptops'), ('monitors', 'Monitors'), ('office_equipment', 'Office equipment'), ('video_surveillance', 'Video surveillance')], default='other', max_length=20, verbose_name='Категории')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст записи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('moderate', models.BooleanField(verbose_name='Модерирование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='feedback.product', verbose_name='Продукт')),
            ],
        ),
    ]
