# Generated by Django 4.0 on 2022-03-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_review_author_alter_review_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moderate',
            field=models.BooleanField(verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='feedback.product', verbose_name='Продукт'),
        ),
    ]
