# Generated by Django 4.0 on 2022-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_review_moderate_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moderate',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
